default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  user: <%= ENV.fetch("POSTGRES_USER") { nil } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { nil } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sure_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sure_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sure_production" } %>
  # For Heroku: limit connections per dyno to avoid connection limit issues
  # Formula: (RAILS_MAX_THREADS * WEB_CONCURRENCY) + SIDEKIQ_CONCURRENCY should be < DB connection limit
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 3 } } %>
